package-lock.json
package.json
src/app.module.ts
src/users/users.service.ts

1. 유저 회원가입 기능 중복 시 에러 반환하게 수정
2. conflickexception을 import하여 중복시 http 409메세지 반환

수정:유저 로그인 기능 관련 코드 수정

---

Back-end/src/auth/auth.controller.spec.ts
Back-end/src/auth/auth.module.ts
Back-end/src/auth/auth.service.spec.ts
Back-end/src/auth/auth.service.ts

PR:auth 관련 코드 변경

---

Back-end/src/course_doc/course_doc.controller.ts
Back-end/src/course_doc/course_doc.module.ts
Back-end/src/courses/courses.controller.ts
Back-end/src/courses/courses.module.ts
Back-end/src/doc_name/doc_name.controller.ts
Back-end/src/doc_name/doc_name.module.ts
Back-end/src/exhibition_intro/exhibition_intro.controller.ts
Back-end/src/exhibition_intro/exhibition_intro.module.ts
Back-end/src/exhibitions/exhibition.entity.ts
Back-end/src/exhibitions/exhibitions.controller.ts
Back-end/src/exhibitions_doc/exhibitions_doc.controller.ts
Back-end/src/exhibitions_doc/exhibitions_doc.module.ts
Back-end/src/exhibitions_member/exhibitions_member.controller.ts
Back-end/src/feedback/feedback.controller.ts
Back-end/src/feedback/feedback.module.ts
Back-end/src/project_doc/project_doc.controller.ts
Back-end/src/project_doc/project_doc.module.ts
Back-end/src/projects/projects.controller.ts
Back-end/src/registration/registration.controller.ts
Back-end/src/registration/registration.module.ts

PR:UseGuard 적용

---

Back-end/src/auth/ownership.decorator.ts
Back-end/src/auth/ownership.guard.ts
Back-end/src/user/users.controller.ts

PR:ownership 폴더 및 파일 추가 , 관련 코드 추가

PR:ownership 폴더 및 파일 추가 , 관련 코드 추가

---

Back-end/src/course/course_doc/course_doc.service.ts
Back-end/src/course/doc_name/doc_name.controller.ts
Back-end/src/course/doc_name/doc_name.service.ts
Back-end/src/course/video/video.service.ts
Back-end/src/course/video_topic/video_topic.service.ts
Back-end/src/main.ts

PR: doc_name & course_doc 로직 수정

PR: doc_name & course_doc 로직 수정

---

Back-end/src/app.module.ts
Back-end/src/course/course_registration/course_registration.controller.spec.ts
Back-end/src/course/course_registration/course_registration.controller.ts
Back-end/src/course/course_registration/course_registration.module.ts
Back-end/src/course/course_registration/course_registration.service.spec.ts
Back-end/src/course/course_registration/course_registration.service.ts
Back-end/src/course/course_registration/dto/create-course_registration.dto.ts
Back-end/src/course/course_registration/dto/update-course_registration.dto.ts
Back-end/src/course/course_registration/entities/course_registration.entity.ts
Back-end/src/course/courses/entities/course.entity.ts
Back-end/src/project/project_registration/entities/registration.entity.ts
Back-end/src/project/project_registration/registration.controller.ts
Back-end/src/project/project_registration/registration.service.ts
Back-end/src/project/projects/entities/project.entity.ts
Back-end/src/user/user.entity.ts

Course registration

---

Back-end/src/course/course_doc/course_doc.controller.ts
Back-end/src/course/course_doc/course_doc.service.ts
Back-end/src/course/doc_name/doc_name.controller.ts
Back-end/src/course/doc_name/doc_name.service.ts

Params modify

---

Back-end/src/app.module.ts
Back-end/src/attendance/attendance.controller.spec.ts
Back-end/src/attendance/attendance.controller.ts
Back-end/src/attendance/attendance.module.ts
Back-end/src/attendance/attendance.service.spec.ts
Back-end/src/attendance/attendance.service.ts
Back-end/src/attendance/dto/check-attendance.dto.ts
Back-end/src/attendance/dto/create-attendance.dto.ts
Back-end/src/attendance/dto/update-attendance.dto.ts
Back-end/src/attendance/dto/update-student-attendance.dto.ts
Back-end/src/attendance/entities/attendance.entity.ts
Back-end/src/course/courses/courses.service.ts
Back-end/src/course/courses/entities/course.entity.ts
Back-end/src/user/user.entity.ts

PR:Attendance기능 추가

---

Back-end/src/course/doc_name/doc_name.controller.ts
Back-end/src/course/doc_name/doc_name.service.ts
Back-end/src/course/video/video.controller.ts

PR: pa_topic_id가 null인 docName 조회 메서드 작성

PR: pa_topic_id가 null인 docName 조회 메서드 작성

---

Back-end/src/course/course_registration/course_registration.controller.ts
Back-end/src/course/course_registration/course_registration.service.ts
Back-end/src/course/courses/courses.controller.ts
Back-end/src/course/doc_name/doc_name.controller.ts
Back-end/src/course/video_topic/video_topic.controller.ts
Back-end/src/project/project_doc/project_doc.controller.ts
Back-end/src/project/projects/projects.controller.ts

PR: 컨벤션 정리 및 엔드포인트 수정

---

Back-end/src/attendance/attendance.controller.ts
Back-end/src/attendance/attendance.service.ts
Back-end/src/attendance/dto/create-attendance.dto.ts

PR:Attendance 수정

---

Back-end/src/exhibition/exhibitions_doc/dto/create-exhibitions_doc.dto.ts
Back-end/src/exhibition/exhibitions_doc/exhibitions_doc.controller.ts
Back-end/src/exhibition/exhibitions_doc/exhibitions_doc.service.ts

수정:Exhibitions 수정

---

Back-end/src/exhibition/exhibition_intro/dto/create-exhibition_intro.dto.ts
Back-end/src/exhibition/exhibition_intro/dto/update-exhibition_intro.dto.ts
Back-end/src/exhibition/exhibition_intro/exhibition_intro.controller.ts
Back-end/src/exhibition/exhibition_intro/exhibition_intro.service.ts
Back-end/src/exhibition/exhibitions_member/dto/create-exhibitions_member.dto.ts
Back-end/src/exhibition/exhibitions_member/dto/update-exhibitions_member.dto.ts
Back-end/src/exhibition/exhibitions_member/exhibitions_member.controller.ts
Back-end/src/exhibition/exhibitions_member/exhibitions_member.service.ts

PR:Exhibitions 수정

---

Back-end/src/attendance/attendance.controller.ts
Back-end/src/attendance/attendance.service.ts

1.getusersincourse 로직변경
2.필요없는 주석 , 로직 변경

수정:attendance 관련 코드 수정

---

Back-end/src/course/course_registration/entities/course_registration.entity.ts
Back-end/src/user/dto/user-courses-projects.response.dto/course.dto.ts
Back-end/src/user/dto/user-courses-projects.response.dto/project.dto.ts
Back-end/src/user/dto/user-courses-projects.response.dto/user-courses-projects.response.dto.ts
Back-end/src/user/users.controller.ts
Back-end/src/user/users.service.ts

PR:User 수정

---

Back-end/src/user/users.controller.ts

PR:user 관련 코드 수정

---

Back-end/src/course/course_registration/course_registration.controller.ts
Back-end/src/course/video/video.controller.ts
Back-end/src/course/video/video.service.ts

PR: pre-signed url

---

Back-end/src/course/course_registration/course_registration.controller.ts
Back-end/src/course/course_registration/course_registration.service.ts

CourseRegistration Request update Dto 수정

Course registration2

---

Back-end/src/app.module.ts

수정: ServeStaticModule.forRoot 주석처리

수정: ServeStaticModule.forRoot 주석처리

---

Back-end/src/course/video_topic/video_topic.service.ts
Back-end/src/exhibition/exhibitions/exhibitions.service.ts
Back-end/src/exhibition/exhibitions_doc/exhibitions_doc.service.ts

PR: exhibition에 AWS 기능 추가

---

Back-end/src/course/course_registration/course_registration.controller.ts
Back-end/src/course/course_registration/course_registration.service.ts
Back-end/src/course/course_registration/dto/get-admin-course_registration.dto.ts
Back-end/src/course/video_topic/dto/user-course-videotopic.response.dto.ts
Back-end/src/user/dto/user-response.dto.ts

PR: Issues 6번 해결 시도(1)

---

Back-end/src/exhibition/exhibitions_member/dto/create-exhibitions_member.dto.ts
Back-end/src/exhibition/exhibitions_member/entities/exhibition_member.entity.ts

수정:exhibition_member 수정

---

Back-end/src/course/course_doc/course_doc.controller.ts
Back-end/src/course/course_doc/course_doc.service.ts
Back-end/src/course/course_registration/entities/course_registration.entity.ts
Back-end/src/course/courses/courses.controller.ts
Back-end/src/course/courses/courses.service.ts
Back-end/src/course/courses/dto/course-with-videotopic.dto.ts
Back-end/src/course/doc_name/doc_name.controller.ts
Back-end/src/course/doc_name/dto/doc_name-with-coursedoc-response.dto.ts
Back-end/src/course/video_topic/dto/create-video_topic.dto.ts
Back-end/src/course/video_topic/dto/update-video_topic.dto.ts
Back-end/src/course/video_topic/dto/video_topic-response.dto.ts
Back-end/src/course/video_topic/dto/video_topic-without-filepath-response.dto.ts
Back-end/src/course/video_topic/entities/video_topic.entity.ts
Back-end/src/course/video_topic/video_topic.controller.ts
Back-end/src/course/video_topic/video_topic.service.ts
Back-end/src/exhibition/exhibitions/exhibitions.controller.ts
Back-end/src/user/user.entity.ts

course
video topic
doc name
course doc
4개에 대한 CRUD 전부 테스팅, GET의 경우 관계에 대한 JSON 반환을 확인
todo: course with courseregistration 부분의 get만 안했음.

수정 & 추가 & 삭제:

---

Back-end/package-lock.json
Back-end/package.json

수정:package.json 수정

---

Back-end/src/course/courses/courses.controller.ts
Back-end/src/course/courses/courses.service.ts
Back-end/src/course/courses/dto/create-course.dto.ts
Back-end/src/course/courses/dto/update-course.dto.ts
Back-end/src/course/courses/entities/course.entity.ts
Back-end/src/course/video/dto/create-video.dto.ts
Back-end/src/course/video/dto/update-video.dto.ts
Back-end/src/course/video/video.controller.ts
Back-end/src/course/video/video.service.ts

PR: Course 프론트연결 최종

---

Back-end/src/course/courses/courses.service.ts
Back-end/src/course/courses/dto/course-with-docname-and-coursedoc.dto.ts
Back-end/src/course/courses/dto/course-with-videotopic.dto.ts
Back-end/src/course/doc_name/doc_name.controller.ts
Back-end/src/course/doc_name/doc_name.service.ts
Back-end/src/course/doc_name/dto/doc_name-with-coursedoc-response.dto.ts

PR: DocName(Doc-Topic) CRD 구현

---

Back-end/src/course/video/dto/video-response.dto.ts
Back-end/src/course/video/video.controller.ts
Back-end/src/course/video/video.service.ts
Back-end/src/course/video_topic/dto/video_topic-with-video-name.dto.ts
Back-end/src/course/video_topic/video_topic.service.ts

PR: video CR 테스트 완료

---

Back-end/src/course/course_registration/course_registration.controller.ts
Back-end/src/course/courses/courses.controller.ts
Back-end/src/course/doc_name/entities/doc_name.entity.ts
Back-end/src/course/video/entities/video.entity.ts

PR: 오류 해결 및 cascade적용

---

Back-end/src/project/feedback/entities/feedback.entity.ts
Back-end/src/project/project_doc/dto/create-project_doc.dto.ts
Back-end/src/project/project_doc/dto/project_doc-response.dto.ts
Back-end/src/project/project_doc/dto/update-project_doc.dto.ts
Back-end/src/project/project_doc/entities/project_doc.entity.ts
Back-end/src/project/project_registration/dto/create-registration.dto.ts
Back-end/src/project/project_registration/dto/update-registration.dto.ts
Back-end/src/project/projects/dto/create-project.dto.ts
Back-end/src/project/projects/dto/project-response.dto.ts
Back-end/src/project/projects/dto/update-project.dto.ts
Back-end/src/project/projects/entities/project.entity.ts

PR: project 관련 dto, entity 수정

---

Back-end/src/auth/ownership.guard.ts
Back-end/src/project/feedback/feedback.service.ts
Back-end/src/project/project_doc_title/dto/doc_title-with-project_doc-response.dto.ts
Back-end/src/project/project_doc_title/dto/update-project_doc_title.dto.ts
Back-end/src/project/project_doc_title/project_doc_title.controller.ts
Back-end/src/project/project_doc_title/project_doc_title.module.ts
Back-end/src/project/project_doc_title/project_doc_title.service.ts

PR: ownership guard와 project 관련 기능 수정 및 추가

PR: ownership guard와 project 관련 기능 수정 및 추가

---

Back-end/src/project/feedback/feedback.service.ts
Back-end/src/project/project_doc_title/dto/doc_title-with-project_doc-response.dto.ts
Back-end/src/project/project_doc_title/dto/project_doc_title-response.dto.ts
Back-end/src/project/project_doc_title/entities/project_doc_title.entity.ts
Back-end/src/project/project_doc_title/project_doc_title.controller.ts
Back-end/src/project/project_doc_title/project_doc_title.service.ts
Back-end/src/project/project_key_doc/project_key_doc.controller.ts
Back-end/src/project/projects/entities/project.entity.ts
Back-end/src/project/projects/projects.controller.ts

PR: project-list, projectmy 3개 작성

PR: project-list, projectmy 3개 작성

---

Back-end/src/project/project_doc/project_doc.service.ts
Back-end/src/project/project_doc_title/dto/create-project_doc_title.dto.ts
Back-end/src/project/project_doc_title/dto/doc_title-with-project_doc-response.dto.ts
Back-end/src/project/project_doc_title/dto/project_doc_title-response.dto.ts
Back-end/src/project/project_doc_title/dto/update-project_doc_title.dto.ts
Back-end/src/project/project_doc_title/entities/project_doc_title.entity.ts
Back-end/src/project/project_doc_title/project_doc_title.controller.ts
Back-end/src/project/project_doc_title/project_doc_title.service.ts

project- 트러블슈팅
